services:
  database:
    container_name: openpulse-postgres
    image: postgres:16
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    container_name: openpulse-api
    image: biku1998/openpulse-api
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      - PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY:-168h}
    ports:
      - ${API_PORT:-8000}:${API_PORT:-8000}
    depends_on:
      - database

  web-client:
    container_name: openpulse-web-client
    image: biku1998/openpulse-web-client
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./web-client
    environment:
      - PORT=${WEB_CLIENT_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - ${WEB_CLIENT_PORT:-5173}:${WEB_CLIENT_PORT:-5173}