services:
  database:
    image: postgres:16
    container_name: openpulse-postgres
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  auth:
    image: openpulse/auth-serice
    container_name: openpulse-auth-service
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./auth
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY:-168h}
    depends_on:
      - database

  kong:
    image: kong:latest
    container_name: openpulse-kong
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    environment:
      KONG_DATABASE: 'off' # DB-less mode
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/kong.yml' # Location of the config file
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_LOG_LEVEL: debug
    ports:
      - '8000:8000'
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    depends_on:
      - auth
