services:
  database:
    env_file:
      - .env

  api:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app:/node_modules

  web-client:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./web-client:/app
      - /app/node_modules